application: grizzlyraccoon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: azulpanda.html
  upload: azulpanda.html
  mime_type: text/html

- url: /seed.html
  static_files: seed.html
  upload: seed.html
  mime_type: text/html

- url: /fantastic.html
  static_files: fantastic.html
  upload: fantastic.html
  mime_type: text/html

- url: /maps.html
  static_files: maps.html
  upload: maps.html
  mime_type: text/html

- url: /(.*)
  static_files: \1
  upload: (.*)